name: CI/CD Build

on:
  workflow_run:
    workflows: ["CI Tests"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v7

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image
        uses: docker/build-push-action@v7
        with:
          context: ./server
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/webshop-clone-server:latest
            ghcr.io/${{ github.repository_owner }}/webshop-clone-server:${{ github.sha }}

      - name: Build and push client image
        uses: docker/build-push-action@v7
        with:
          context: ./client
          push: true
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/webshop-clone-client:latest
            ghcr.io/${{ github.repository_owner }}/webshop-clone-client:${{ github.sha }}

  deploy:
    needs: build-and-push
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.VPS_SECRET_KEY }}
          script: |
            set -e
            cd ${{ secrets.DEPLOY_PATH }}

            podman compose -f docker-compose.prod.yml pull

            podman compose -f docker-compose.prod.yml run --rm server \
            npx prisma migrate deploy

            podman compose -f docker-compose.prod.yml up -d

            podman image prune -f